version: '3.8'

x-env: &worker-env
  environment:
    REDIS_HOST: cache
    REDIS_PORT: 6379
    REDIS_PASS: ${REDIS_PASS}
    API_HOST: s3mock
    API_PORT: 5000

services:
  s3mock:
    container_name: s3mock
    build:
      context: .
      dockerfile: s3mock/Dockerfile

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    depends_on:
      - s3mock
    volumes:
      - cache:/data

  worker1:
    container_name: worker1
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - cache
    <<: *worker-env

  worker2:
    container_name: worker2
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - cache
    <<: *worker-env


volumes:
  cache:
    driver: local